# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-08-23T12:41:00+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel


class SourcesGetResponseItem(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    tags: Optional[List[str]] = None


class DefaultConfig(BaseModel):
    modelTemperature: Optional[float] = None
    topK: Optional[int] = None
    maxOutputTokens: Optional[int] = None
    systemPrompt: Optional[str] = None
    similarityCutoff: Optional[float] = None


class ConfigGetResponse(BaseModel):
    models: Optional[List[str]] = None
    defaultConfig: Optional[DefaultConfig] = None


class GeneratePostRequest(BaseModel):
    query: str
    tags: Optional[List[str]] = None
    model: Optional[str] = None
    modelTemperature: Optional[float] = None
    topK: Optional[int] = None
    maxOutputTokens: Optional[int] = None
    systemPrompt: Optional[str] = None
    similarityCutoff: Optional[float] = None


class Event(Enum):
    answer = "answer"
    reference = "reference"
    stop = "stop"


class ReferenceData(BaseModel):
    source: Optional[str] = None
    text: Optional[str] = None
    similarityScore: Optional[float] = None
    page: Optional[int] = None
    url: Optional[str] = None


class GeneratePostResponse(BaseModel):
    event: Event
    data: Union[str, List[ReferenceData]]


class SourcesGetResponse(BaseModel):
    tag: Optional[str] = None
    items: List[str]
